name: Python package

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out your repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements
          pip install pytest
      - name: Running test cases
        run: pytest

